### PR TITLE
Go version of Animal

### PR DESCRIPTION
**Pull request by beforan**

### CODE REVIEW

**Comment by drom** [comment]
let me know when you think you are ready (LMKWYTYAR)

**Comment by beforan** [comment]
things should be slightly more idiomatic now.
Also it's no longer a single file; configurable data is in `data.go` and type definitions (structs, consts) are in `types.go`

Because of not using the original game's text, and slightly different usage, it doesn't load the existing `text.json`, but has its own text dictionary in `data.go`, though the properties mimic those of `text.json` for consistency.

I'm pretty happy with this. I'm sure there are future improvements, but it works like the original game, while benefiting from quality of life improvements (like not using a coded string array for all questions and answers, and reusable functions for most bits).

**Comment by drom** [comment]
Looks awesome. Now it is becoming multilingual peace of art -- does it make sense to move Go version into `/go/` folder? I can do the same with JavaScript version :smirk:

**Comment by drom** [comment]
fixes #2

**Pull request merged**
