### PR TITLE
Add perl version

### PR DESCRIPTION
**Pull request by sdeseille**
Hello

I just finished Perl version.
I hope you will be ok to merge it to your repository.

regards
sdeseille

### CODE REVIEW

**Comment by drom** [comment]
@sdeseille Great job. Have you tested it?

**Comment by sdeseille** [comment]
Hello, yes of course. It is the reason why you can see many commit :)
Do you want i add some test ?

**Comment by drom** [comment]
It seems that I have problem with path to `data.pl` file.
```
drom@drom:~/work/github/drom/animal/perl> ./animal.pl
Can't locate data.pl in @INC (@INC contains: /usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl) at ./animal.pl line 7.
```

**Comment by sdeseille** [comment]
how, i see. What is your Perl version ?

**Comment by drom** [comment]
v5.26.1

**Comment by sdeseille** [comment]
Ok, I understood. It is a behaviour linked to Perl 5.26. 
Explanation here: https://www.effectiveperlprogramming.com/2017/01/v5-26-removes-dot-from-inc/

I will push an update to correct that.

**Comment by drom** [comment]
@sdeseille I have only pretty simple test for all implementations:

`./animal.pl < ../test/test.txt > log.txt`

The log should look like:
```
PLAY 'GUESS THE ANIMAL'
THINK OF AN ANIMAL AND THE COMPUTER WILL TRY TO GUESS IT...
ARE YOU THINKING OF AN ANIMAL ? DOES IT SWIM ? IS IT A FISH ? THE ANIMAL YOU WERE THINKING OF WAS A ? PLEASE TYPE IN A QUESTION THAT WOULD differ A elephant FROM A FISH: WHY NOT TRY ANOTHER ANIMAL
ARE YOU THINKING OF AN ANIMAL ? ANIMALS I ALREADY KNOW ARE:
[
    "DOES IT SWIM",
    [
        "big",
        "elephant",
        "FISH"
    ],
    "BIRD"
]
ARE YOU THINKING OF AN ANIMAL ? O.K.  SEE YOU LATER.  HOPE YOU HAD FUN PLAYING!!
```

**Pull request merged**
